define([], function() {
    return {
        "PropertyPaneDescription": "Set featured content items to display in the web part",
        "BasicGroupName": "Manage Content",
        "ContentListFieldLabel": "Featured Content Editor",
        "ManageContentLabel": "Manage Featured Content",
        "ImageFieldName": "Image",
        "TitleFieldName": "Title",
        "UrlFieldName": "URL",
        "NewTabFieldName": "Open in New Tab",
        "TitlePlaceholder": "Featured",

        "AddNewButtonText": "Add Featured Content",
        "PlaceholderButtonText": "Add a link",
        "SaveButtonText": "Save",
        "SelectButtonText": "Open",
        "CancelButtonText": "Cancel",
        "SelectFromLinkLabel": "From a link",
        "SelectFromLinkDescription": "Paste a link to a site, page, document, list or library",
        "SelectFromSiteTitle": "Select files from site picker view. Use toolbar menu to perform operations, breadcrumbs to navigate between folders and arrow keys to navigate within the list",

        "EditItemGeneralLabel": "General",
        "EditItemGeneralTitleLabel": "Title",
        "EditItemGeneralTitlePreCountLabel": "80 Max Character Limit - ",
        "EditItemGeneralTitlePostCountLabel": " Characters Remaining",
        "EditItemGeneralTitleErrorText": " This field is limited to 80 characters",
        "EditItemGeneralDescriptionLabel": "Description",
        "EditItemGeneralAlternateLabel": "Alternate Text for Image",
        "EditItemGeneralDescriptionPreCountLabel": "130 Max Character Limit - ",
        "EditItemGeneralDescriptionPostCountLabel": " Characters Remaining",
        "EditItemGeneralDescriptionErrorText": " This field is limited to 130 characters",
        "EditItemGeneralContentLabel": "Content (HTML allowed)",
        "EditItemGeneralSelectLinkLabel": "Select a link from a document or page",
        "EditItemGeneralSelectLinkButtonText": "Change",
        "EditItemGeneralOpenTabLabel": "Open link in a new window",
        "EditItemImageLabel": "Image",
        "EditItemImageEntryLabel": "Current Image",
        "EditItemImageAlternateText": "Alternate Text for Image",
        "EditItemGuidanceLabel": "Guidance",
        "RequiredValueErrorText": "This field is highly recommended.",

        "DeleteItemConfirmMessage": "Are you sure you want to delete this box button?",

        'WebPartPropertySwitcherGroupLabel': 'Web Part Properties',
        'SwitchToBasicLabel': 'Select to return to Basic Web Part Properties Menu',
        'SwitchToBasicButtonText': 'Basic Features',
        'SwitchToAdvancedLabel': 'Select to view the Advanced Web Part Properties Menu',
        'SwitchToAdvancedButtonText': 'Advanced Features',
        "OnLabel": "Yes",
        "OffLabel": "No",

        'AdvancedListModeGroupLabel': 'List',
        'AdvancedEnableListModeLabel': 'Enable list mode',
        'AdvancedEnableListModeInfo': 'When enabled, items will be stored in a list and support filtering',

        "LayoutLabel": "Layouts",
        "LayoutSelectorLabel": "Select Layout",
        "TitleOnlyLabel": "Title Only",
        "TitleDescriptionLabel": "Title & Description",
        "StackedLabel": "Stacked",
        "AltStackedLabel": "Alternating Stacked"
    }
});