define([], function () {
  return {
    "SearchQuerySettingsGroupName": "Configuración de consulta de búsqueda",
    "SearchSettingsGroupName": "Opciones de Búqueda",
    "SearchQueryKeywordsFieldLabel": "Palabras clave de consulta de búsqueda",
    "QueryTemplateFieldLabel": "Plantilla de consulta",
    "SelectedPropertiesFieldLabel": "Propiedades seleccionadas",
    "LoadingMessage": "Los resultados se estan cargando, por favor, espere...",
    "EnableLocalizationLabel": "Habilitar los valores de localización de taxonomia en los refinadores y resultados",
    "EnableLocalizationOnLabel": "Localización habilitada",
    "EnableLocalizationOffLabel": "Localización deshabilitada",
    "MaxResultsCount": "Número de eleemntos devueltos por página",
    "NoResultMessage": "No hay resultados para mostrar",
    "FilterPanelTitle": "Filtros disponibles",
    "FilterResultsButtonLabel": "Filtros",
    "SelectedFiltersLabel": "Filtros seleccionados",
    "SearchResultsLabel": "Resultados de Búsqueda",
    "RemoveAllFiltersLabel": "Eliminar todos los filtros",
    "UsePaginationWebPartLabel": "Conectar a Web Part de Paginación de Búsqueda",
    "ShowResultsCountLabel": "Mostrar el contador de resultados",
    "ShowBlankLabel": "Mostrar en blanco si no ha resultado",
    "ShowBlankEditInfoMessage": "No se devuelve ningún resultado para esta consulta. Este Web Part permanecerá en blanco en el modo de visualización según los parámetros.",
    "NoFilterConfiguredLabel": "Ningún filtro configurado",
    "SearchQueryPlaceHolderText": "Consulta de Búsqueda en formato KQL",
    "EmptyFieldErrorMessage": "Este campo no puede ser vacío",
    "PlaceHolderEditLabel": "Editar",
    "PlaceHolderConfigureBtnLabel": "Configurar",
    "PlaceHolderIconText": "Web Part de Resultados de Búsqueda",
    "PlaceHolderDescription": "Este componente muestra los resultados de búsqueda con paginación",
    "ResultSourceIdLabel": "Identificador de origen de resultados",
    "InvalidResultSourceIdMessage": "Indentificador Inválido",
    "EnableQueryRulesLabel": "Habilitar reglas de consulta",
    "StylingSettingsGroupName": "Opciones de Estilo",
    "SelectedPropertiesFieldDescription": "Especificar las propiedades para recuperar de los resultados de búsqueda.",
    "SearchQueryKeywordsFieldDescription": "Utilice palabras clave de consulta de búsqueda predefinidas para recuperar un conjunto estático de resultados.",
    "CountMessageLong": "<b>{0}</b> resultados de '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> resultados",
    "CancelButtonText": "Cancelar",
    "DialogButtonLabel": "Estilos",
    "DialogButtonText": "Editar plantilla",
    "DialogTitle": "Editar plantilla de resultados",
    "SaveButtonText": "Guardar",
    "ListLayoutOption": "Lista",
    "TilesLayoutOption": "Tiles",
    "DebugLayoutOption": "Depurar",
    "CustomLayoutOption": "Personalizado",
    "ResultsLayoutLabel": "Diseño de resultados",
    "SliderLayoutOption": "Carrusel",
    "TemplateUrlFieldLabel": "Utilice una URL de plantilla externa",
    "TemplateUrlPlaceholder": "https://myfile.html",
    "ErrorTemplateExtension": "La plantilla debe ser un archivo. htm o. html válido",
    "ErrorTemplateResolve": "No se puede resolver la plantilla especificada. Detalles del error: '{0}'",
    "WebPartTitle": "Web Part Título",
    "HandlebarsHelpersDescription": "Habilitar funciones de momment y helpers de handlebars. Ver https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens para más información.",
    "PromotedResultsLabel": "Resultado/s Promocionado/s",
    "PanelCloseButtonAria": "Cerrar",
    "UseRefinersWebPartLabel": "Conectar con Web Part Refinadores de Búsqueda",
    "UseRefinersFromComponentLabel": "Utilice refinadores de este componente",
    "UsePaginationFromComponentLabel": "Utilice la paginación de este componente",
    "customTemplateFieldsLabel": "Valores de campo de plantilla personalizada",
    "customTemplateFieldsPanelHeader": "Valores de campo de plantilla personalizada",
    "customTemplateFieldsConfigureButtonLabel": "Configurar",
    "customTemplateFieldTitleLabel": "Nombre de campo",
    "customTemplateFieldPropertyLabel": "Buscar propiedad",
    "Sort": {
      "SortableFieldsPropertyPaneField": "Propiedades ordenables",
      "SortableFieldsDescription": "Especifica las propiedades clasificables que los usuarios pueden usar en la interfaz de usuario. Solo se puede usar una propiedad a la vez para ordenar y anulará el orden de búsqueda especificado en el WP, si existe.",
      "SortPropertyPaneFieldLabel": "Criterio de ordenación",
      "SortListDescription": "Especifique el criterio de ordenación para los resultados de búsqueda. Esto solo se aplica cuando no se han establecido filtros manuales (por ejemplo, campos ordenables)",
      "SortDirectionAscendingLabel": "Ascendente",
      "SortDirectionDescendingLabel": "Descendente",
      "SortErrorMessage": "Propiedad de búsqueda no válida (Compruebe si la propiedad administrada es ordenable).",
      "SortPanelSortFieldLabel": "Clasificar en campo",
      "SortPanelSortFieldAria": "Seleccione un campo",
      "SortPanelSortFieldPlaceHolder": "Seleccione un campo",
      "SortPanelSortDirectionLabel": "Ordenar dirección",
      "SortableFieldManagedPropertyField": "Ordenar la propiedad administrada",
      "SortableFieldDisplayValueField": "Nombre de campo para mostrar",
      "EditSortableFieldsLabel": "Editar campos ordenables",
      "EditSortLabel": "Edite el criterio de ordenación"
    },
    "Synonyms": {
      "EditSynonymLabel": "Editar sinónimos",
      "SynonymListDescription": "Especifique todos los sinónimos que se utilizarán en la búsqueda. Cada término de búsqueda se completará con todos los sinónimos asociados cuando la consulta se envíe al servidor. Si un sinónimo contiene más de una palabra, tiene que estar entre comillas dobles.",
      "SynonymPropertyPanelFieldLabel": "Configure sinónimos",
      "SynonymListTerm": "Término",
      "SynonymListSynonyms": "Sinónimos",
      "SynonymIsTwoWays": "¿Dos maneras?",
      "SynonymListSynonymsExemple": "Portátil, \"Escritorio con monitor\"",
      "SynonymListTermExemple": "Ordenador"
    },
    "TermNotFound": "(El término con ID '{0}' no se encuentra)",
    "UseDefaultSearchQueryKeywordsFieldLabel": "Utilice una consulta de búsqueda predeterminada",
    "DefaultSearchQueryKeywordsFieldLabel": "Consulta de búsqueda predeterminada",
    "DefaultSearchQueryKeywordsFieldDescription": "Esta consulta se usará cuando el valor del origen de datos aún esté vacío.",
    "ResultTypes": {
      "ResultTypeslabel": "Tipos de resultado",
      "ResultTypesDescription": "Agregue aquí las plantillas de visualización que se utilizarán para los elementos de resultados según una o más condiciones. Las condiciones se evalúan en el orden configurado y la plantilla externa tiene prioridad sobre las plantillas en línea. Asegúrese de que las propiedades administradas que utiliza estén presentes en las 'Propiedades seleccionadas' de este Web Part.",
      "EditResultTypesLabel": "Editar tipos de resultado",
      "ConditionPropertyLabel": "Propiedad administrada",
      "ConditionValueLabel": "Valo de condición",
      "CondtionOperatorValue": "Operador",
      "ExternalUrlLabel": "URL de plantilla externa",
      "EqualOperator": "Iguales",
      "ContainsOperator": "Contiene",
      "StartsWithOperator": "Empieza por",
      "NotNullOperator": "No es nulo",
      "GreaterOrEqualOperator": "Mayor o igual",
      "GreaterThanOperator": "Mayor que",
      "LessOrEqualOperator": "Menor o igual",
      "LessThanOperator": "Menos que"
    },
    "QueryCultureLabel": "Idioma de la solicitud de búsqueda",
    "QueryCultureUseUiLanguageLabel": "Utilizar idioma de interfaz"
  }
});