define([], function() {
  return {
    "SearchQuerySettingsGroupName": "Configuration de la requête de recherche",
    "SearchSettingsGroupName": "Paramètres de recherche",
    "SearchQueryKeywordsFieldLabel": "Mots clés de recherche",
    "QueryTemplateFieldLabel": "Modèle de requête",
    "SelectedPropertiesFieldLabel": "Propriétés à récupérer",
    "LoadingMessage": "Les résultats sont en cours de chargement, veuillez patienter...",
    "MaxResultsCount": "Nombre de résulats à récupérer par page",
    "EnableLocalizationLabel": "Activer la traduction des termes de taxonomie pour les filtres et les résultats",
    "EnableLocalizationOnLabel": "Traduction activée",
    "EnableLocalizationOffLabel": "Traduction  désactivée",
    "NoResultMessage": "Aucun résultat à afficher.",
    "FilterPanelTitle": "Filtres disponibles",
    "FilterResultsButtonLabel": "Filtrer",
    "SelectedFiltersLabel": "Filtre(s) appliqué(s)",
    "SearchResultsLabel": "Résultats d recherche",
    "RemoveAllFiltersLabel": "Supprimer tous les filtres",
    "UsePaginationWebPartLabel": "Connectez un Web Part de pagination de recherche",
    "ShowResultsCountLabel": "Afficher le nombre de résultats",
    "ShowBlankLabel": "Ne rien afficher si aucun résultat",
    "ShowBlankEditInfoMessage": "Aucun résultat pour cette requête. Ce composant Web Part restera vide en mode affichage conformément aux paramètres.",
    "NoFilterConfiguredLabel": "Aucun filtre configuré",
    "SearchQueryPlaceHolderText": "Requête de recherche au format KQL",
    "EmptyFieldErrorMessage": "Ce champ ne peut pas être vide",
    "PlaceHolderEditLabel": "Éditer",
    "PlaceHolderConfigureBtnLabel": "Configurer",
    "PlaceHolderIconText": "Web Part de recherche",
    "PlaceHolderDescription": "Ce composant affiche une liste de résulats de recherche avec pagination",
    "ResultSourceIdLabel": "Identifiant de l'origine de résultats",
    "InvalidResultSourceIdMessage": "Identifiant invalide",
    "EnableQueryRulesLabel": "Activer les règles de requête",
    "IncludeOneDriveResultsLabel": "Inclure les résultats personnels OneDrive",
    "StylingSettingsGroupName": "Options d'affichage",
    "SelectedPropertiesFieldDescription": "Propriétés à récupérer des résulats de recherche.",
    "SearchQueryKeywordsFieldDescription": "Utilisez une requête de recherche prédéfinie pour obtenir un ensemble de résultats statique.",
    "CountMessageLong": "<b>{0}</b> résultats pour '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> résultats",
    "CancelButtonText": "Annuler",
    "DialogButtonLabel": "Éditer le modèle",
    "DialogButtonText": "Éditer le modèle",
    "DialogTitle": "Éditer le modèle de résulat",
    "SaveButtonText": "Enregistrer",
    "SimpleListLayoutOption": "List simple",
    "DetailsListLayoutOption": "Liste détailléé",
    "TilesLayoutOption": "Tuiles",
    "CustomLayoutOption": "Personnalisé",
    "DebugLayoutOption": "Débogage",
    "SliderLayoutOption": "Caroussel",
    "PeopleLayoutOption": "Personnes",
    "ResultsLayoutLabel": "Disposition des résultats",
    "TemplateUrlFieldLabel": "Utiliser un fichier modèle externe",
    "TemplateUrlPlaceholder": "https://myfile.html",
    "ErrorTemplateExtension": "Le file modèle doit être un fichier .htm ou .html valide",
    "ErrorTemplateResolve": "Impossible de résoudre le fichier. Détails: '{0}'",
    "WebPartTitle": "Titre de web part",
    "HandlebarsHelpersDescription": "Activer les fonctions de moment et handlebars helpers. Voir https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens pour plus d'informations.",
    "PromotedResultsLabel": "Résultat(s) promu(s)",
    "PanelCloseButtonAria":"Proche",
    "UseRefinersWebPartLabel": "Connectez un Web Part de filtres de recherche",
    "UseRefinersFromComponentLabel": "Utiliser les filtres à partir de ce composant",
    "UsePaginationFromComponentLabel": "Utiliser la pagination à partir de ce composant",
    "customTemplateFieldsLabel": "Valeurs de champ de modèle personnalisé",
    "customTemplateFieldsPanelHeader": "Valeurs de champ de modèle personnalisé",
    "customTemplateFieldsConfigureButtonLabel": "Configurer",
    "customTemplateFieldTitleLabel": "Nom du champ",
    "customTemplateFieldPropertyLabel": "Propriété de recherche",
    "Sort": {
      "SortableFieldsPropertyPaneField":"Propriétés triables",
      "SortableFieldsDescription": "Propriétés à utiliser pour permettre aux utilisateurs de trier les résultats depuis l'interface. Le tri ne peut être porter que sur une seule propriété à la fois et surpasse le tri par défaut des résulats si existant.",
      "SortPropertyPaneFieldLabel":"Ordre de tri",
      "SortListDescription": "Spécifiez l'ordre de tri des résultats de recherche. Ceux-ci ne s'appliqueront que si aucun champ de tri n'a été configurée pour ce Web Part (i.e propriétés triables)",
      "SortDirectionAscendingLabel":"Ascendant",
      "SortDirectionDescendingLabel":"Descendant",
      "SortErrorMessage":"Propriété de recherche non valide (Vérifiez si la propriété managée est triable).",
      "SortPanelSortFieldLabel":"Trier sur le champ",
      "SortPanelSortFieldAria":"Sélectionner un champ",
      "SortPanelSortFieldPlaceHolder":"Sélectionner un champ",
      "SortPanelSortDirectionLabel":"Direction de tri",
      "SortableFieldManagedPropertyField": "Propriété gérée de tri",
      "SortableFieldDisplayValueField": "Intitulé du champ à afficher",
      "EditSortableFieldsLabel": "Éditer les champs de tri",
      "EditSortLabel": "Éditer l'ordre de tri",
      "SortInvalidSortableFieldMessage": "Cette propriété n'est pas triable"
    },
    "Synonyms": {
      "EditSynonymLabel": "Modifier les synonymes",
      "SynonymListDescription": "Inclure tous les synonymes utilisés pour la recherche. Chaque terme sera bonifié avec tous les synonymes associés au moment de lancer la requête au serveur. Si un synonyme contient plus d'un mot, celui-ci doit être encapsulé par des double guillements.",
      "SynonymPropertyPanelFieldLabel": "Configurer les synonymes",
      "SynonymListTerm": "Terme",
      "SynonymListSynonyms": "Synonymes",
      "SynonymIsTwoWays": "Bidirectionnel?",
      "SynonymListSynonymsExemple": "Portable, \"Tour et écran\"",
      "SynonymListTermExemple": "Ordinateur"
    },
    "TermNotFound": "(Terme avec l'ID '{0}' non trouvé)",
    "UseDefaultSearchQueryKeywordsFieldLabel": "Utiliser une requête initiale",
    "DefaultSearchQueryKeywordsFieldLabel": "Requête de recherche par défaut",
    "DefaultSearchQueryKeywordsFieldDescription": "Cette requête sera utilisée par défault dans le cas où la valeur de la source de données est encore vide.",
    "ResultTypes": {
      "ResultTypeslabel": "Types de résultats",
      "ResultTypesDescription": "Ajoutez ici les modèles d'affichage à utiliser pour les éléments correspondant à une ou plusieurs conditions. Les conditions sont évaluées dans l'ordre et les modèles externes ont priorité sur ceux définis à même le composant. Vérifiez également que les propriétés gérées de recherche utilisées comme conditions sont présentes dans le paramètre 'Propriétés à récupérer' de ce Web Part.",
      "InlineTemplateContentLabel": "Contenu du modèle",
      "EditResultTypesLabel": "Éditer les types de résultats",
      "ConditionPropertyLabel": "Propriété gérée",
      "ConditionValueLabel": "Valeur de la condition",
      "CondtionOperatorValue": "Opérateur",
      "ExternalUrlLabel": "URL du template externe",
      "EqualOperator": "Égal",
      "NotEqualOperator": "N'est pas égal",
      "ContainsOperator": "Contient",
      "StartsWithOperator": "Commence par",
      "NotNullOperator": "N'est pas nul",
      "GreaterOrEqualOperator": "Supérieur ou égal",
      "GreaterThanOperator": "Supérieur à",
      "LessOrEqualOperator": "Inférieur ou égal",
      "LessThanOperator": "Inférieur"
    },
    "QueryCultureLabel": "Langue de la requête",
    "QueryCultureUseUiLanguageLabel": "Utiliser la langue de l'interface",
    "TemplateParameters": {
      "TemplateParametersGroupName": "Options d'affichage",
      "EnableItemPreview": "Activer l'aperçu de résultat",
      "ShowFileIcon": "Afficher l'icône de fichier",
      "ManageDetailsListColumnDescription": "Ajouter, modifier ou supprimer des colonnes pour cet affichage. Vous pouvez soit utiliser la valeur d'une propriété de recherche directement ou bien spécifier une expression Handlebars en tant que valeur. Pour chacun des champs, vous pouvez également injecter votre propre code HTML",
      "ManageDetailsListColumnLabel": "Gérer les colonnes",
      "ManageTilesFieldsLabel": "Gérer les champs de la carte",
      "ManagePeopleFieldsLabel": "Gérer les champs de personne",
      "ManagePeopleFieldsPanelDescriptionLabel": "Ici vous pouvez associer la valeur de chaque champ aux zones d'élements 'Personne' correspondantes. Vous pouvez soit utiliser la valeur d'une propriété de recherche directement ou bien spécifier une expression Handlebars en tant que valeur.",
      "ManageTilesFieldsPanelDescriptionLabel": "Ici vous pouvez associer la valeur de chaque champ aux zones de la carte correspondantes. Vous pouvez soit utiliser la valeur d'une propriété de recherche directement ou bien spécifier une expression Handlebars en tant que valeur. Pour certains champ, lorsque indiqué, vous pouvez également injecter votre propre code HTML.",
      "PlaceholderNameFieldLabel": "Nom",
      "PlaceholderValueFieldLabel": "Valeur",
      "ValueColumnLabel": "Valeur",
      "DisplayNameColumnLabel": "Intitulé de la colonne",
      "UseHandlebarsExpressionLabel": "Utiliser une expression Handlebars",
      "MinimumWidthColumnLabel": "Largeur minimum (px)",
      "MaximumWidthColumnLabel": "Largeur maximum (px)",
      "SortableColumnLabel": "Triable",
      "ResizableColumnLabel": "Extensible",
      "MultilineColumnLabel": "Plusieurs lignes",
      "LinkToItemColumnLabel": "Lien vers l'élément",
      "SupportHTMLColumnLabel": "Supporte HTML",
      "CompactModeLabel": "Mode compact",
      "SliderAutoPlayDuration": "Avancer les slides toutes les X millisecondes",
      "SliderAutoPlay": "Lecture automatique",
      "SliderPauseAutoPlayOnHover": "Pause lors du survolement",
      "SliderGroupCells": "Nombre d'éléments à grouper par slide",
      "SliderShowPageDots": "Afficher la navigation",
      "SliderWrapAround": "Défilement inifini",
      "PersonaSizeOptionsLabel": "Taille de l'image",
      "PersonaSizeExtraSmall": "Très petit",
      "PersonaSizeSmall": "Petit",
      "PersonaSizeRegular": "Normal",
      "PersonaSizeLarge": "Grand",
      "PersonaSizeExtraLarge": "Très grand",
      "LivePersonaDisableHover": "Désactiver l'affichage des informations au survolement"
    },
    "ManagedPropertiesListPlaceHolder": "Sélectionnez ou ajoutez une propriété gérée"
  }
});
