define([], function () {
  return {
    "SearchQuerySettingsGroupName": "Zoekopdracht configuratie",
    "SearchSettingsGroupName": "Zoek instellingen",
    "SearchQueryKeywordsFieldLabel": "Zoekopdracht trefwoorden",
    "QueryTemplateFieldLabel": "Zoekopdracht template",
    "SelectedPropertiesFieldLabel": "Geselecteerde eigenschappen",
    "LoadingMessage": "Resultaten worden geladen, een moment geduld...",
    "EnableLocalizationLabel": "Inschakelen van gelokaliseerde taxonomy waarden voor verfijningen en resultaten",
    "EnableLocalizationOnLabel": "Lokalisatie ingeschakeld",
    "EnableLocalizationOffLabel": "Lokalisatie uitgeschakeld",
    "MaxResultsCount": "Aantal resultaten per pagina",
    "NoResultMessage": "Geen resultaten gevonden",
    "FilterPanelTitle": "Beschikbare filters",
    "FilterResultsButtonLabel": "Filters",
    "SelectedFiltersLabel": "Geselecteerde filters",
    "SearchResultsLabel": "Zoekresultaten",
    "RemoveAllFiltersLabel": "Verwijder alle filters",
    "UsePaginationWebPartLabel": "Verbind met een Zoekpaginering webonderdeel",
    "ShowResultsCountLabel": "Toon aantal resultaten",
    "ShowBlankLabel": "Toon niets als er geen resultaten zijn",
    "ShowBlankEditInfoMessage": "Geen resultaten voor deze zoekopdracht. Het webonderdeel blijft leeg",
    "NoFilterConfiguredLabel": "Geen filter geconfigureerd",
    "SearchQueryPlaceHolderText": "Zoekopdracht in KQL formaat",
    "EmptyFieldErrorMessage": "Dit veld mag niet leeg zijn",
    "PlaceHolderEditLabel": "Bewerken",
    "PlaceHolderConfigureBtnLabel": "Configuren",
    "PlaceHolderIconText": "Zoekresultaten webonderdeel",
    "PlaceHolderDescription": "Dit webonderdeel toont zoekresultaten met paginering",
    "ResultSourceIdLabel": "Id van de resultatenbron",
    "InvalidResultSourceIdMessage": "Incorrecte id",
    "EnableQueryRulesLabel": "Query rules ingeschakeld",
    "IncludeOneDriveResultsLabel": "Persoonlijke OneDrive-resultaten opnemen",
    "StylingSettingsGroupName": "Opmaak opties",
    "SelectedPropertiesFieldDescription": "Geef de eigenschappen op die moeten worden opgehaald uit de zoekresultaten.",
    "SearchQueryKeywordsFieldDescription": "Gebruik vooraf gedefinieerde zoekwoorden om een ​​statische set resultaten op te halen.",
    "CountMessageLong": "<b>{0}</b> resultaten voor '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> resultaten",
    "CancelButtonText": "Annuleren",
    "DialogButtonLabel": "Styling",
    "DialogButtonText": "Bewerk template",
    "DialogTitle": "Bewerk resultatentemplate",
    "SaveButtonText": "Opslaan",
    "SimpleListLayoutOption": "Lijst",
    "DetailsListLayoutOption": "Detaillijst",
    "TilesLayoutOption": "Tegels",
    "CustomLayoutOption": "Aangepast",
    "DebugLayoutOption": "Debug",
    "SliderLayoutOption": "Carousel",
    "PeopleLayoutOption": "Personen",
    "ResultsLayoutLabel": "Resultaten opmaak",
    "TemplateUrlFieldLabel": "Gebruik een externe template URL",
    "TemplateUrlPlaceholder": "https://myfile.html",
    "ErrorTemplateExtension": "De template moet een geldig .htm of .html bestand zijn",
    "ErrorTemplateResolve": "Kan het opgegeven sjabloon niet vinden. Foutdetails: '{0}'",
    "WebPartTitle": "Webonderdeel titel",
    "HandlebarsHelpersDescription": "Activeer functies van moment en handlebars. Zie: https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens voor meer informatie.",
    "PromotedResultsLabel": "Gepromoveerde resultaten",
    "PanelCloseButtonAria": "Sluiten",
    "UseRefinersWebPartLabel": "Verbind met een zoekverfijningen webonderdeel",
    "UseRefinersFromComponentLabel": "Gebruik verfijningen van dit webonderdeel",
    "UsePaginationFromComponentLabel": "Gebruik paginering van dit webonderdeel",
    "customTemplateFieldsLabel": "Aangepaste sjabloonveldwaarden",
    "customTemplateFieldsPanelHeader": "Aangepaste sjabloonveldwaarde",
    "customTemplateFieldsConfigureButtonLabel": "Configureren",
    "customTemplateFieldTitleLabel": "Veldnaam",
    "customTemplateFieldPropertyLabel": "Zoekeigenschappen",
    "Sort": {
      "SortableFieldsPropertyPaneField": "Sorteerbare eigenschappen",
      "SortableFieldsDescription": "Configureert de sorteerbare eigenschappen die in de UI kunnen worden gebruikt. Er kan slechts een actieve sortering worden gekozen.",
      "SortPropertyPaneFieldLabel": "Sorteervolgorde",
      "SortListDescription": "De standaard sorteervolgorde. Wordt alleen gebruikt als er geen handmatige keuze is gemaakt.",
      "SortDirectionAscendingLabel": "Oplopend",
      "SortDirectionDescendingLabel": "Aflopend",
      "SortErrorMessage": "Ongeldige zoekeigenschap (controleer of de eigenschap sorteerbaar is)",
      "SortPanelSortFieldLabel": "Sorteer op veld",
      "SortPanelSortFieldAria": "Selecteer een eigenschapp",
      "SortPanelSortFieldPlaceHolder": "Selecteer een veld",
      "SortPanelSortDirectionLabel": "Sorteervolgorde",
      "SortableFieldManagedPropertyField": "Sorteer beheerde eigenschap",
      "SortableFieldDisplayValueField": "Veldnaam om te tonen",
      "EditSortableFieldsLabel": "Bewerk sorteerbare velden",
      "EditSortLabel": "Bewerk sorteervolgorde",
      "SortInvalidSortableFieldMessage": "Deze eigenschap is niet sorteerbaar"
    },
    "Synonyms": {
      "EditSynonymLabel": "Bewerk synoniemen",
      "SynonymListDescription": "Geef alle synoniemen op die worden gebruikt bij het zoeken. Elke zoekterm wordt uitgebreid met alle bijbehorende synoniemen wanneer de zoekopdracht naar de server wordt verzonden. Als een synoniem meer dan één woord bevat, moet dit tussen dubbele aanhalingstekens worden geplaatst.",
      "SynonymPropertyPanelFieldLabel": "Configureer synoniemen",
      "SynonymListTerm": "Term",
      "SynonymListSynonyms": "Synoniemen",
      "SynonymIsTwoWays": "Twee-wegs?",
      "SynonymListSynonymsExemple": "Laptop, \"Desktop met monitor\"",
      "SynonymListTermExemple": "Computer"
    },
    "TermNotFound": "(Term met ID '{0}' niet gevonden)",
    "UseDefaultSearchQueryKeywordsFieldLabel": "Gebruik een standaard zoekopdracht",
    "DefaultSearchQueryKeywordsFieldLabel": "Standaard zoekopdracht",
    "DefaultSearchQueryKeywordsFieldDescription": "De zoekopdracht wordt gebruikt als de data bron waarde leeg is.",
    "ResultTypes": {
      "ResultTypeslabel": "Resultaatsoorten",
      "ResultTypesDescription": "Voeg hier de weergavesjablonen toe die moeten worden gebruikt voor resultaatsoorten, volgens één of meer voorwaarden. Voorwaarden worden geëvalueerd in de geconfigureerde volgorde en externe sjabloon heeft voorrang op inline-sjablonen. Zorg ervoor dat de beheerde eigenschappen die u gebruikt aanwezig zijn in de 'Geselecteerde eigenschappen' van dit webonderdeel.",
      "InlineTemplateContentLabel": "Inline template",
      "EditResultTypesLabel": "Bewerk Resultaatsoorten",
      "ConditionPropertyLabel": "Beheerde eigenschap",
      "ConditionValueLabel": "Voorwaardelijke waarde",
      "CondtionOperatorValue": "Operator",
      "ExternalUrlLabel": "Externe Template Url",
      "EqualOperator": "Is gelijk aan",
      "NotEqualOperator": "Niet gelijk",
      "ContainsOperator": "Bevat",
      "StartsWithOperator": "Begint met",
      "NotNullOperator": "Is niet leeg",
      "GreaterOrEqualOperator": "Groter dan of gelijk aan",
      "GreaterThanOperator": "Groter dan",
      "LessOrEqualOperator": "Minder dan of gelijk aan",
      "LessThanOperator": "Minder dan"
    },
    "QueryCultureLabel": "Taal van de zoekaanvraag",
    "QueryCultureUseUiLanguageLabel": "Taal van de gebruikersinterface",
    "TemplateParameters": {
      "TemplateParametersGroupName": "Template opties",
      "EnableItemPreview": "Voorbeeldweergave inschakelen",
      "ShowFileIcon": "Bestandsicoon inschakelen",
      "ManageDetailsListColumnDescription": "Velden toevoegen, bewerken of verwijderen in de detail lijstweergave. Je kan ofwel de beheerde eigenschap rechtstreeks gebruiken zonder transformatie of de Handlebars syntax gebruiken in het veld kolomwaarde. Elk veld ondersteunt ook HTML.",
      "ManageDetailsListColumnLabel": "Beheer kolommen",
      "ManageTilesFieldsLabel": "Beheer velden op de kaart",
      "ManagePeopleFieldsLabel": "Beheer velden van personen",
      "ManagePeopleFieldsPanelDescriptionLabel": "Hier kan je elk veld mappen met de overeenkomstige placeholders. Je kan ofwel de beheerde eigenschap rechtstreeks gebruiken zonder transformatie of de Handlebars syntax gebruiken in het veld kolomwaarde.",
      "ManageTilesFieldsPanelDescriptionLabel": "Hier kan je elk veld mappen met de overeenkomstige placeholders. Je kan ofwel de beheerde eigenschap rechtstreeks gebruiken zonder transformatie of de Handlebars syntax gebruiken in het veld kolomwaarde. Wanneer aangegeven, kan je ook je eigen HTML injecteren in sommige velden.",
      "PlaceholderNameFieldLabel": "Naam",
      "PlaceholderValueFieldLabel": "Waarde",
      "ValueColumnLabel": "Kolomwaarde",
      "DisplayNameColumnLabel": "Kolom weergavenaam",
      "UseHandlebarsExpressionLabel": "Gebruik Handlebars syntax",
      "MinimumWidthColumnLabel": "Minimum breedte (px)",
      "MaximumWidthColumnLabel": "Maximum breedte (px)",
      "SortableColumnLabel": "Sorteerbaar",
      "ResizableColumnLabel": "Breedte aanpasbaar",
      "MultilineColumnLabel": "Meerdere lijnen",
      "LinkToItemColumnLabel": "Link naar item",
      "SupportHTMLColumnLabel": "HTML toestaan",
      "CompactModeLabel": "Compacte weergave",
      "SliderAutoPlayDuration": "Naar volgende item gaan, iedere (seconden)",
      "SliderAutoPlay": "Automatisch afspelen",
      "SliderPauseAutoPlayOnHover": "Pauzeren bij mouse-over",
      "SliderGroupCells": "Aantal elementen groeperen in slides",
      "SliderShowPageDots": "Beletselteken tussen pagina's weergeven",
      "SliderWrapAround": "Oneindige scrolling",
      "PersonaSizeOptionsLabel": "afbeeldingsgrootte",
      "PersonaSizeExtraSmall": "Extra klein",
      "PersonaSizeSmall": "Klein",
      "PersonaSizeRegular": "Normaal",
      "PersonaSizeLarge": "Groot",
      "PersonaSizeExtraLarge": "Extra groot",
      "LivePersonaDisableHover": "Geen weergave bij mouse-over"
    },
    "ManagedPropertiesListPlaceHolder": "Selecteer of voeg een beheerde eigenschap toe"
  }
});
