define([], function () {
  return {
    "SearchQuerySettingsGroupName": "Zoekopdracht configuratie",
    "SearchSettingsGroupName": "Zoek instellingen",
    "SearchQueryKeywordsFieldLabel": "Zoekopdracht trefwoorden",
    "QueryTemplateFieldLabel": "Zoekopdracht template",
    "SelectedPropertiesFieldLabel": "Geselecteerde eigenschappen",
    "LoadingMessage": "Resultaten worden geladen, een moment gedult...",
    "EnableLocalizationLabel": "Inschakelen van gelokaliseerde taxonomy waarden voor verfijningen en resultaten",
    "EnableLocalizationOnLabel": "Lokalisatie ingeschakeld",
    "EnableLocalizationOffLabel": "Lokalisatie uitgeschakeld",
    "MaxResultsCount": "Aantal resultaten per pagina",
    "NoResultMessage": "Geen resultaten gevonden",
    "FilterPanelTitle": "Beschikbare filters",
    "FilterResultsButtonLabel": "Filters",
    "SelectedFiltersLabel": "Geselecteerde filters",
    "SearchResultsLabel": "Zoekresultaten",
    "RemoveAllFiltersLabel": "Verwijder alle filters",
    "UsePaginationWebPartLabel": "Verbind met een Zoekpaginering webonderdeel",
    "ShowResultsCountLabel": "Toon aanta resulten",
    "ShowBlankLabel": "Toon als leeg bij geen resultaten",
    "ShowBlankEditInfoMessage": "Geen resultaten voor deze zoekopdracht. Het webonderdeel blijft leeg",
    "NoFilterConfiguredLabel": "Geen filter geconfigureerd",
    "SearchQueryPlaceHolderText": "Zoekopdracht in KQL formaat",
    "EmptyFieldErrorMessage": "Dit veld mag niet leeg zijn",
    "PlaceHolderEditLabel": "Bewerken",
    "PlaceHolderConfigureBtnLabel": "Configuren",
    "PlaceHolderIconText": "Zoekresultaten webonderdeel",
    "PlaceHolderDescription": "Dit webonderdeel toont zoekresultaten met paginering",
    "ResultSourceIdLabel": "Result Source Identifier",
    "InvalidResultSourceIdMessage": "Invalide identifier",
    "EnableQueryRulesLabel": "Query rules ingeschakeld",
    "StylingSettingsGroupName": "Opmaak opties",
    "SelectedPropertiesFieldDescription": "Geef de eigenschappen op die moeten worden opgehaald uit de zoekresultaten.",
    "SearchQueryKeywordsFieldDescription": "Gebruik vooraf gedefinieerde zoekwoorden om een ​​statische set resultaten op te halen.",
    "CountMessageLong": "<b>{0}</b> resultaten voor '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> resultaten",
    "CancelButtonText": "Annuleren",
    "DialogButtonLabel": "Styling",
    "DialogButtonText": "Bewerk template",
    "DialogTitle": "Bewerk resultatentemplate",
    "SaveButtonText": "Opslaan",
    "ListLayoutOption": "Lijst",
    "TilesLayoutOption": "Tegels",
    "CustomLayoutOption": "Aangepast",
    "ResultsLayoutLabel": "Resultaten opmaak",
    "TemplateUrlFieldLabel": "Gebruik een externe template URL",
    "TemplateUrlPlaceholder": "https://myfile.html",
    "ErrorTemplateExtension": "De template moet een valide .htm of .html bestand zijn",
    "ErrorTemplateResolve": "Kan de opgegeven sjabloon niet oplossen. Foutdetails: '{0}'",
    "WebPartTitle": "Webonderdeel titel",
    "HandlebarsHelpersDescription": "Activeer functies van moment- en handlebars. Zie: https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens voor meer informatie.",
    "PromotedResultsLabel": "Gepromoveerde resultaten",
    "PanelCloseButtonAria": "Sluiten",
    "UseRefinersWebPartLabel": "Verbind met een zoekverfijningen webonderdeel",
    "UseRefinersFromComponentLabel": "Gebruik verfijningen van dit webonderdeel",
    "UsePaginationFromComponentLabel": "Gebruik paginering van dit webonderdeel",
    "customTemplateFieldsLabel": "Aangepaste sjabloonveldwaarden",
    "customTemplateFieldsPanelHeader": "Aangepaste sjabloonveldwaarde",
    "customTemplateFieldsConfigureButtonLabel": "Configureren",
    "customTemplateFieldTitleLabel": "Veldnaam",
    "customTemplateFieldPropertyLabel": "Zoekeigenschappen",
    "Sort": {
      "SortableFieldsPropertyPaneField": "Sorteerbare eigenschappen",
      "SortableFieldsDescription": "Configureerd de sorteerbare eigenschappen die in de UI kunnen worden gebruikt. Er kan slechts een actieve sortering worden gekozen.",
      "SortPropertyPaneFieldLabel": "Sorteer volgorde",
      "SortListDescription": "De standaard sorteer volgorde. Wordt alleen gebruikt als er geen handmatige keuze is gemaakt.",
      "SortDirectionAscendingLabel": "Oplopend",
      "SortDirectionDescendingLabel": "Aflopend",
      "SortErrorMessage": "Ongeldige zoekeigenschap (controleer of de eigenschap sorteerbaar is)",
      "SortPanelSortFieldLabel": "Sorteer op veld",
      "SortPanelSortFieldAria": "Selecteer een eigenschapp",
      "SortPanelSortFieldPlaceHolder": "Selecteer een veld",
      "SortPanelSortDirectionLabel": "Sorteer volgorde",
      "SortableFieldManagedPropertyField": "Sorteer beheerde eigenschap",
      "SortableFieldDisplayValueField": "Veldnaam om te tonen",
      "EditSortableFieldsLabel": "Bewerk sorteerbare velden",
      "EditSortLabel": "Bewerk sorteervolgorde"
    },
    "Synonyms": {
      "EditSynonymLabel": "Bewerk synoniemen",
      "SynonymListDescription": "Geef alle synoniemen op die worden gebruikt bij het zoeken. Elke zoekterm wordt uitgebreid met alle bijbehorende synoniemen wanneer de zoekopdracht naar de server wordt verzonden. Als een synoniem meer dan één woord bevat, moet dit tussen dubbele aanhalingstekens worden geplaatst.",
      "SynonymPropertyPanelFieldLabel": "Configureer synoniemen",
      "SynonymListTerm": "Term",
      "SynonymListSynonyms": "Synoniemen",
      "SynonymIsTwoWays": "Twwee-wegs?",
      "SynonymListSynonymsExemple": "Laptop, \"Desktop met monitor\"",
      "SynonymListTermExemple": "Computer"
    },
    "TermNotFound": "(Term met ID '{0}' niet gevonden)",
    "UseDefaultSearchQueryKeywordsFieldLabel": "Gebruik een standaard zoekopdracht",
    "DefaultSearchQueryKeywordsFieldLabel": "Standaard zoekopdracht",
    "DefaultSearchQueryKeywordsFieldDescription": "De zoekopdracht wordt gebruikt als de data bron waarde leeg is.",
    "ResultTypes": {
      "ResultTypeslabel": "Resultaat Typen",
      "ResultTypesDescription": "Voeg hier de weergavesjablonen toe die moeten worden gebruikt voor resultaatitems volgens een of meer voorwaarden. Voorwaarden worden geëvalueerd in de geconfigureerde volgorde en externe sjabloon heeft voorrang op inline-sjablonen. Zorg ervoor dat de beheerde eigenschappen die u gebruikt aanwezig zijn in de 'Geselecteerde eigenschappen' van dit webonderdeel.",
      "EditResultTypesLabel": "Bewerk Resultaat Typen",
      "ConditionPropertyLabel": "Beheerde eigenschap",
      "ConditionValueLabel": "Voorwaardelijke waarde",
      "CondtionOperatorValue": "Operator",
      "ExternalUrlLabel": "Externe Template Url",
      "EqualOperator": "Is gelijk aan",
      "ContainsOperator": "Bevat",
      "StartsWithOperator": "Begint met",
      "NotNullOperator": "Is niet leeg",
      "GreaterOrEqualOperator": "Groter dan of gelijk aan",
      "GreaterThanOperator": "Groter dan",
      "LessOrEqualOperator": "Minder dan of gelijk aan",
      "LessThanOperator": "Minder dan"
    },
    "QueryCultureLabel": "Taal van de zoek aanvraag",
    "QueryCultureUseUiLanguageLabel": "Gebruikers interface taal"
  }
});
