define([], function() {
    return {
        "CreateButton": "Create",
        "CancelButton": "Cancel",
        "SPListCreate": "Create a List",
        "SPListCreatePlaceholder": "title",
        "SPListQueryOpenList": "Edit list in new window",
        "SPListQueryList": "Select a list that has already been created",
        "SPListQueryOrderBy": "Order By",
        "SPListQueryArranged": "Arranged",
        "SPListQueryMax": "Max",
        "SPListQueryAdd": "Add filter",
        "SPListQueryRemove": "Remove",
        "SPListQueryOperatorEq": "Equals",
        "SPListQueryOperatorNe": "Not Equals",
        "SPListQueryOperatorStartsWith": "Starts With",
        "SPListQueryOperatorSubstringof": "Sub String of",
        "SPListQueryOperatorLt": "Less than",
        "SPListQueryOperatorLe": "Less or equal to",
        "SPListQueryOperatorGt": "Greater than",
        "SPListQueryOperatorGe": "Greater or equal to",
        "SPListFilterCompareType": "Filter Compare",
        "SPListFilterCompareAll": "All",
        "SPListFilterCompareAny": "Any",

        "ImageSelectorTypeAuto": "Auto-selected image",
        "ImageSelectorTypeCustom": "Custom image",

        "CustomImageLabel": "Custom Image",
        "ChangeImageButtonText": "Change",

        "SelectButtonText": "Open",
        "CancelButtonText": "Cancel",
        "SelectFromLinkLabel": "From a link",
        "SelectFromLinkDescription": "Paste a link to a site, page, document, list or library",
        "SelectFromSiteTitle": "Select files from site picker view. Use toolbar menu to perform operations, breadcrumbs to navigate between folders and arrow keys to navigate within the list",
        "NoPreviewText": "No default image available. Select a custom image",

        "OpenModalTitle": "Open in Modal",
        "RichTextToolbarBoldTitle": "Bold",
        "RichTextToolbarItalicTitle": "Italic",
        "RichTextToolbarNumberedListTitle": "Numbered List",
        "RichTextToolbarBulletedListTitle": "Bulleted List",
        "RichTextModalRTEPivotLabel": "Text",
        "RichTextModalHTMLPivotLabel": "HTML",
        "RichTextModalSaveText": "OK",
        "RichTextModalCancelText": "Cancel",
        "GroupSortMessageSegment1": "Choose sort order for groups."
    }
});