define([], function() {
    return {
        "RefinersConfigurationGroupName": "Refiner settings",
        "ShowBlankLabel": "Show blank if no result",
        "WebPartTitle": "Web part title",
        "StylingSettingsGroupName": "Styling options",
        "AppliedRefinersLabel": "Applied refiners",
        "PlaceHolderEditLabel": "Edit",
        "PlaceHolderConfigureBtnLabel": "Configure",
        "PlaceHolderIconText": "Search Refiners Web Part",
        "PlaceHolderDescription": "This component displays search refiners",
        "NoFilterConfiguredLabel": "No filter available",
        "RemoveAllFiltersLabel": "Remove all filters",
        "ShowBlankEditInfoMessage": "No filter to display. This Web Part will remain blank in display mode according to parameters.",
        "RefinersConfiguration": "Refiners configuration",
        "SearchResultsLabel": "Search results",
        "SearchQueryLabel": "Search query",
        "FilterResultsButtonLabel": "Filters",
        "SelectedFiltersLabel": "Selected filters:",
        "RefinerLayoutLabel": "Filters layout",
        "ConnectToSearchResultsLabel": "Connect to search results Web Part",
        "Refiners": {
            "RefinersFieldLabel": "Refiners",
            "RefinerManagedPropertyField": "Filter managed property",
            "RefinerDisplayValueField": "Filter name to display",
            "RefinerTemplateField": "Refiner template",
            "RefinersFieldDescription": "Specifies managed properties used as refiners. If there are no values for a filter property, it won't appear in the panel.",
            "EditRefinersLabel": "Edit refiners",
            "AvailableRefinersLabel": "Available refiners",
            "ApplyFiltersLabel": "Apply",
            "ClearFiltersLabel": "Clear",
            "ShowExpanded": "Expand filter by default",
            "Templates": {
                "RefinementItemTemplateLabel": "Default refinement item",
                "MutliValueRefinementItemTemplateLabel": "Multi-value refinement item",
                "DateRangeRefinementItemLabel": "Date range",
                "FixedDateRangeRefinementItemLabel": "Date range (fixed intervals)",
                "DateFromLabel": "From",
                "DateTolabel": "To",
                "DatePickerStrings": {
                    "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    "days": ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                    "shortDays": ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
                    "goToToday": 'Go to today',
                    "prevMonthAriaLabel": 'Go to previous month',
                    "nextMonthAriaLabel": 'Go to next month',
                    "prevYearAriaLabel": 'Go to previous year',
                    "nextYearAriaLabel": 'Go to next year',
                    "closeButtonAriaLabel": 'Close date picker',
                    "isRequiredErrorMessage": 'Start date is required.',
                    "invalidInputErrorMessage": 'Invalid date format.'
                },
                "DateIntervalStrings": {
                    "AnyTime": "Any time",
                    "PastDay": "Past 24 hours",
                    "PastWeek": "Past week",
                    "PastMonth": "Past month",
                    "Past3Months": "Past 3 months",
                    "PastYear": "Past year",
                    "Older": "Older than a year"
                },
                "RefinerSortTypeLabel": "Refiner sort type",
                "RefinerSortTypeAlphabetical": "Alphabetical",
                "RefinerSortTypeByNumberOfResults": "By number of results",
                "RefinerSortTypeSortOrderLabel": "Sort order",
                "RefinerSortTypeSortDirectionAscending": "Ascending",
                "RefinerSortTypeSortDirectionDescending": "Descending"
            }
        },
    }
});