define([], function() {
    return {
        "RefinersConfigurationGroupName": "Configuración de RefinadoresRefiner settings",
        "ShowBlankLabel": "Mostrar en blanco si no hay resultados",
        "WebPartTitle": "Título de Web part",
        "StylingSettingsGroupName": "Opciones de estilo",
        "AppliedRefinersLabel": "Refinadores aplicados",
        "PlaceHolderEditLabel": "Editar",
        "PlaceHolderConfigureBtnLabel": "Configurar",
        "PlaceHolderIconText": "Web Part de refinadores de búsqueda",
        "PlaceHolderDescription": "Este componente muestra los refinadores de búsqueda",
        "NoFilterConfiguredLabel": "No hay filtro disponible",
        "RemoveAllFiltersLabel": "Eliminar todos los filtros",
        "ShowBlankEditInfoMessage": "No hay filtro para mostrar. Este Web Part permanecerá en blanco en el modo de visualización de acuerdo a los parámetros.",
        "RefinersConfiguration": "Configuración de los Refinadores",
        "SearchResultsLabel": "Resultados de Búsqueda",
        "SearchQueryLabel": "Consulta de Búsqueda",
        "FilterResultsButtonLabel": "Filtros",
        "SelectedFiltersLabel": "Filtros seleccionados:",
        "RefinerLayoutLabel": "Diseño de filtros",
        "ConnectToSearchResultsLabel": "Conectar al Web Part de Resultados de Búsqueda",
        "Refiners": {
            "RefinersFieldLabel": "Refinadores",
            "RefinerManagedPropertyField": "Filtrar la propiedad administrada",
            "RefinerDisplayValueField": "Nombre del filtro para mostrar",
            "RefinerTemplateField": "Plantilla de refinador",
            "RefinersFieldDescription": "Especifica las propiedades administradas utilizadas como refinadores. Si no hay valores para una propiedad de filtro, no aparecerá en el panel.",
            "EditRefinersLabel": "Editar refinadores",
            "AvailableRefinersLabel": "Refinadores disponibles",
            "ApplyFiltersLabel": "Aplicar",
            "ClearFiltersLabel": "Limpiar",
            "ShowExpanded": "Expandir filtro predeterminado",
            "Templates": {
                "RefinementItemTemplateLabel": "Elemento de refinamiento predeterminado",
                "MutliValueRefinementItemTemplateLabel": "Elemento de refinamiento multivalor",
                "DateRangeRefinementItemLabel": "Rango Fecha",
                "FixedDateRangeRefinementItemLabel": "Rango Fecha (intervalos fijos)",
                "DateFromLabel": "De",
                "DateTolabel": "Hasta",
                "DatePickerStrings": {
                    "months": ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    "shortMonths": ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    "days": ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                    "shortDays": ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
                    "goToToday": 'Ir a hoy',
                    "prevMonthAriaLabel": 'Ir al mes anterior',
                    "nextMonthAriaLabel": 'Ir al mes siguiente',
                    "prevYearAriaLabel": 'Ir al año anterior',
                    "nextYearAriaLabel": 'Ir al año siguiente',
                    "closeButtonAriaLabel": 'Cerrar seleccionador de fecha',
                    "isRequiredErrorMessage": 'Fecha de Inicio es requerida.',
                    "invalidInputErrorMessage": 'Formato de Fecha Inválido.'
                },
                "DateIntervalStrings": {
                    "AnyTime": "Cualquier hora",
                    "PastDay": "Últimas 24 horas",
                    "PastWeek": "Semana anterior",
                    "PastMonth": "Mes anterior",
                    "Past3Months": "Últimos 3 meses",
                    "PastYear": "Año pasado",
                    "Older": "Antigüedad superior a un año"
                },
                "RefinerSortTypeLabel": "Ordenar refinador por tipo",
                "RefinerSortTypeAlphabetical": "Alfabéticamente",
                "RefinerSortTypeByNumberOfResults": "Por número de resultados",
                "RefinerSortTypeSortOrderLabel": "Criterio de ordenación",
                "RefinerSortTypeSortDirectionAscending": "Ascendente",
                "RefinerSortTypeSortDirectionDescending": "Descendente"
            }
        },
    }
});