define([], function() {
    return {
        "RefinersConfigurationGroupName": "Configuration des filtres",
        "ShowBlankLabel": "Ne rien afficher si aucun résultat",
        "WebPartTitle": "Titre de web part",
        "StylingSettingsGroupName": "Options d'affichage",
        "AppliedRefinersLabel": "Filtre(s) appliqué(s)",
        "PlaceHolderEditLabel": "Éditer",
        "PlaceHolderConfigureBtnLabel": "Configurer",
        "PlaceHolderIconText": "Filtres de recherche Web Part",
        "PlaceHolderDescription": "Ce composant affiche les filtres de recherche",
        "NoFilterConfiguredLabel": "Aucun filtre à afficher",
        "RemoveAllFiltersLabel": "Supprimer tous les filtres",
        "ShowBlankEditInfoMessage": "Aucun filtre à afficher. Ce composant Web Part restera vide en mode affichage conformément aux paramètres.",
        "RefinersConfiguration": "Configuration des filtres",
        "SearchResultsLabel": "Résultats de recherche",
        "SearchQueryLabel": "Requête de recherche",
        "FilterPanelTitle": "Filtres disponibles",
        "FilterResultsButtonLabel": "Filtrer",
        "RefinerLayoutLabel": "Disposition des filtres",
        "ConnectToSearchResultsLabel": "Se connecter au composant de recherche",
        "Refiners": {
            "RefinersFieldLabel": "Filtres",
            "RefinersFieldDescription": "Configurez ici les propriétés gerées à utiliser comme filtres. Si il n'existe pas de valeurs pour le filtre spécifié, il n'apparaîtra pas dans le panneau.",
            "RefinerManagedPropertyField": "Propriété gérée de filtre",
            "RefinerDisplayValueField": "Intitulé du filtre à afficher",
            "RefinerTemplateField": "Modèle de filtre",
            "EditRefinersLabel": "Éditer les filtres",
            "AvailableRefinersLabel": "Filtre(s) disponible(s)",
            "ApplyFiltersLabel": "Appliquer",
            "ClearFiltersLabel": "Effacer",
            "ShowExpanded": "Mode développé par défaut",
            "Templates": {
                "RefinementItemTemplateLabel": "Filtre par défaut",
                "MutliValueRefinementItemTemplateLabel": "Filtre à valeurs multiples",
                "DateRangeRefinementItemLabel": "Sélecteur de dates",
                "FixedDateRangeRefinementItemLabel": "Sélecteur de dates (intervalles fixes)",
                "DateFromLabel": "Du",
                "DateTolabel": "Jusqu'au",
                "DatePickerStrings": {
                    "months": ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
                    "shortMonths": ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jui', 'Jui', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
                    "days": ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
                    "shortDays": ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
                    "goToToday": "Aujourd'hui",
                    "prevMonthAriaLabel": 'Mois précédent',
                    "nextMonthAriaLabel": 'Mois suivant',
                    "prevYearAriaLabel": "Année précédente",
                    "nextYearAriaLabel": "Année suivante",
                    "closeButtonAriaLabel": 'Fermer le sélecteur de date',
                    "isRequiredErrorMessage": 'La date de début est requise.',
                    "invalidInputErrorMessage": 'Format de date invalide.'
                },
                "DateIntervalStrings": {
                    "AnyTime": "Indifférent",
                    "PastDay": "Dernières 24 heures",
                    "PastWeek": "Semaine dernière",
                    "PastMonth": "Mois dernier",
                    "Past3Months": "3 derniers mois",
                    "PastYear": "Année dernière",
                    "Older": "Antérieur à un an"
                },
                "RefinerSortTypeLabel": "Trier selon ce critère",
                "RefinerSortTypeAlphabetical": "Alphabétique",
                "RefinerSortTypeByNumberOfResults": "Par nombre de résultats",
                "RefinerSortTypeSortOrderLabel": "Ordre de tri",
                "RefinerSortTypeSortDirectionAscending": "Ascendant",
                "RefinerSortTypeSortDirectionDescending": "Descendant"
            }
        },
    }
});