define([], function() {
    return {
        "RefinersConfigurationGroupName": "Verfijner instellingen",
        "ShowBlankLabel": "Toon niets als er geen resultaten zijn",
        "WebPartTitle": "Webonderdeel titel",
        "StylingSettingsGroupName": "Weergave opties",
        "AppliedRefinersLabel": "Toegepaste verfijners",
        "PlaceHolderEditLabel": "Bewerken",
        "PlaceHolderConfigureBtnLabel": "Configureren",
        "PlaceHolderIconText": "Zoekverfijningen webonderdeel",
        "PlaceHolderDescription": "Dit component toont zoekverfijningen",
        "NoFilterConfiguredLabel": "Geen filters geconfigureerd",
        "RemoveAllFiltersLabel": "Verwijder alle filters",
        "ShowBlankEditInfoMessage": "Geen filters om te tonen. Het webonderdeel blijft leeg in de weergave modus.",
        "RefinersConfiguration": "Verfijningen configuratie",
        "SearchResultsLabel": "Zoekresultaten",
        "SearchQueryLabel": "Zoekopdracht",
        "FilterResultsButtonLabel": "Filters",
        "SelectedFiltersLabel": "Geselecteerde filters:",
        "RefinerLayoutLabel": "Filters weergave",
        "ConnectToSearchResultsLabel": "Verbind met een zoek webonderdeel",
        "Refiners": {
            "RefinersFieldLabel": "Verfijningen",
            "RefinerManagedPropertyField": "Filter beheerde eigenschap",
            "RefinerDisplayValueField": "Filter naam om te tonen",
            "RefinerTemplateField": "Verfijningssjabloon",
            "RefinersFieldDescription": "Specificeer de eigenschappen die als verfijner moeten worden getoond. Lege filters worden niet getoond.",
            "EditRefinersLabel": "Bewerk verfijners",
            "AvailableRefinersLabel": "Beschikbare verfijners",
            "ApplyFiltersLabel": "Toepassen",
            "ClearFiltersLabel": "Opschonen",
            "ShowExpanded": "Vouw filters standaard uit",
            "Templates": {
                "RefinementItemTemplateLabel": "Standaard verfijningsitem",
                "MutliValueRefinementItemTemplateLabel": "Multi-value verfijningsitem",
                "DateRangeRefinementItemLabel": "Datumbereik",
                "FixedDateRangeRefinementItemLabel": "Datumbereik (vaste intervallen)",
                "DateFromLabel": "Van",
                "DateTolabel": "Tot",
                "DatePickerStrings": {
                    "months": ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 'Juli', 'Augustus', 'September', 'Oktober', 'November', 'December'],
                    "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    "days": ['Zondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
                    "shortDays": ['Z', 'M', 'D', 'W', 'D', 'V', 'Z'],
                    "goToToday": 'Ga naar vandaag',
                    "prevMonthAriaLabel": 'Ga naar vorige maand',
                    "nextMonthAriaLabel": 'Ga naar volgende maand',
                    "prevYearAriaLabel": 'Ga naar vorig jaar',
                    "nextYearAriaLabel": 'Ga naar volgend jaar',
                    "closeButtonAriaLabel": 'Sluit datumprikker',
                    "isRequiredErrorMessage": 'Start datum is verplicht.',
                    "invalidInputErrorMessage": 'Invalide datumformat.'
                },
                "DateIntervalStrings": {
                    "AnyTime": "Elk tijdstip",
                    "PastDay": "Afgelopen 24 uur",
                    "PastWeek": "Afgelopen week",
                    "PastMonth": "Afgelopen maand",
                    "Past3Months": "Afgelopen 3 maanden",
                    "PastYear": "Afgelopen jaar",
                    "Older": "Ouder dan een jaar"
                },
                "RefinerSortTypeLabel": "Verijning sorteertype",
                "RefinerSortTypeAlphabetical": "Alfabetisch",
                "RefinerSortTypeByNumberOfResults": "Aantal resultaten",
                "RefinerSortTypeSortOrderLabel": "Sorteervolgorde",
                "RefinerSortTypeSortDirectionAscending": "Oplopend",
                "RefinerSortTypeSortDirectionDescending": "Aflopend"
            }
        },
    }
});