define([], function() {
    return {
        "PropertyPaneDescription": "Configure the web part to display the list items",
        "ListQueryGroupName": "",
        "FieldMappingGroupName": "Field Mappings",
        "DescriptionFieldLabel": "Description Field",
        "ShowIconFieldLabel": "Show Icons By Links?",
        "GroupLinksFieldLabel": "Group Links By Field?",
        "NotConfiguredMessage": "Please configure the web part to display links.",
        "TitlePlaceholder": "Links",
        "ExpandDefaultLabel": "Show groups links expanded by default",

        "BasicGroupName": "Manage Content",
        "ContentListFieldLabel": "Hub Link Editor",
        "ManageContentLabel": "Manage Hub Link",
        "ImageFieldName": "Image",
        "TitleFieldName": "Title",
        "UrlFieldName": "URL",
        "NewTabFieldName": "Open in New Tab",

        "AddNewButtonText": "Add Hub Link",
        "PlaceholderButtonText": "Add a link",
        "SaveButtonText": "Save",
        "SelectButtonText": "Open",
        "CancelButtonText": "Cancel",
        "SelectFromLinkLabel": "From a link",
        "SelectFromLinkDescription": "Paste a link to a site, page, document, list or library",
        "SelectFromSiteTitle": "Select files from site picker view. Use toolbar menu to perform operations, breadcrumbs to navigate between folders and arrow keys to navigate within the list",

        "EditItemGeneralLabel": "General",
        "EditItemGeneralTitleLabel": "Title",
        "EditItemGeneralTitlePreCountLabel": "80 Max Character Limit - ",
        "EditItemGeneralTitlePostCountLabel": " Characters Remaining",
        "EditItemGeneralTitleErrorText": " This field is limited to 80 characters",
        "EditItemGeneralDescriptionLabel": "Description",
        "EditItemGeneralAlternateLabel": "Alternate Text for Image",
        "EditItemGeneralDescriptionPreCountLabel": "130 Max Character Limit - ",
        "EditItemGeneralDescriptionPostCountLabel": " Characters Remaining",
        "EditItemGeneralDescriptionErrorText": " This field is limited to 130 characters",
        "EditItemGeneralGroupByLabel": "Group",
        "EditItemGeneralGroupByPreCountLabel": "80 Max Character Limit - ",
        "EditItemGeneralGroupByPostCountLabel": " Characters Remaining",
        "EditItemGeneralGroupByErrorText": " This field is limited to 80 characters",
        "EditItemGeneralSelectLinkLabel": "Select a link from a document or page",
        "EditItemGeneralSelectLinkButtonText": "Change",
        "EditItemGeneralOpenTabLabel": "Open link in a new window",
        "EditItemIconLabel": "Icon",
        "EditItemIconEntryLabel": "Enter Font Awesome Icon",
        "EditItemIconEntryPlaceholder": "Example: fa-link",
        "EditItemIconEntryLinkText": "View all icons available",
        "EditItemImageLabel": "Image",
        "EditItemImageEntryLabel": "Current Image",
        "EditItemImageAlternateText": "Alternate Text for Image",
        "EditItemGuidanceLabel": "Guidance",

        "DeleteItemConfirmMessage": "Are you sure you want to delete this box button?",

        'WebPartPropertySwitcherGroupLabel': 'Web Part Properties',
        'SwitchToBasicLabel': 'Select to return to Basic Web Part Properties Menu',
        'SwitchToBasicButtonText': 'Basic Features',
        'SwitchToAdvancedLabel': 'Select to view the Advanced Web Part Properties Menu',
        'SwitchToAdvancedButtonText': 'Advanced Features',
        "OnLabel": "Yes",
        "OffLabel": "No",

        'AdvancedListModeGroupLabel': 'List',
        'AdvancedEnableListModeLabel': 'Enable list mode',
        'AdvancedEnableListModeInfo': 'When enabled, items will be stored in a list and support filtering',

        "TileFontColorLabel": "Font Color",
        "TileBorderColorLabel": "Border Color",
        "TileBackgroundColorLabel": "Background Color",

        "ThemePrimaryColor": "Primary Theme Color",
        "ThemeSecondaryColor": "Secondary Theme Color",
        "ThemeTertiaryColor": "Tertiary Theme Color",
        "ThemePrimaryText": "Primary Theme Text Color",
        "WhiteColor": "White",
        "BlackColor": "Black",
        "TransparentColor": "Transparent",

        'LayoutLabel': 'Layout',
        'LayoutSelectorLabel': 'Layout',
        'ItemLayoutLabel': 'Round Icon',
        'ListLayoutLabel': 'List',
        'GroupedListLayoutLabel': 'Grouped List',
        "IconTopLayoutLabel": "Tiles",
        "IconLeftLayoutLabel": "Square Icon",

        'ShowDescriptionLabel': 'Show Description',
        'GroupSortLabel': 'Reorder Groups',
        'RequiredValueErrorText': 'This field is highly recommended.'
    }
});