define([], function() {
	return {
		PropertyPaneDescription: 'Configure the WebPart settings',
		SettingsGroupName: 'Settings',
    SchemaPropertyButtonLabel: 'Configure Site Designs Schema',
    SchemaPropertyEditorCancelButtonLabel: 'Cancel',
    SchemaPropertyEditorOkButtonLabel: 'Ok',
    SchemaPropertyEditorDialogTitle: 'Set the schema',
    PropertyIsComplexTypeMessage: 'This value is a complex object type',
    UseJsonEditorMessage: 'Use the JSON editor instead',
		LABEL_createSPList: 'Create a List',
		LABEL_setSiteLogo: 'Set the site Logo',
		LABEL_joinHubSite: 'Join a Hub Site',
		LABEL_triggerFlow: 'Trigger a Flow',
		LABEL_addNavLink: 'Add a Navigation Link',
		LABEL_applyTheme: 'Apply a theme to the site',
		LABEL_setTitle: 'Set the title',
		LABEL_setDescription: 'Set the description',
		LABEL_addSPField: 'Add a field',
		LABEL_deleteSPField: 'Delete a field',
		LABEL_addContentType: 'Add a Content Type',
		LABEL_removeContentType: 'Remove a Content Type',
		LABEL_setSPFieldCustomFormatter: 'Set a field custom formatter',
		PROP_listName: 'The name of the List',
		PROP_templateType: 'The List template type',
		PROP_subactions: 'The sub actions',
		PROP_url: 'Url',
		PROP_displayName: 'The display name',
		PROP_isWebRelative: 'Is the Url relative to site',
		PROP_themeName: 'The name of the Theme',
		PROP_hubSiteId: 'The Id of the Hub Site',
		PROP_name: 'Name',
		PROP_parameters: 'Parameters',
		PROP_title: 'Title',
		PROP_description: 'Description',
		PROP_fieldType: 'Type of the field',
		PROP_isRequired: 'Is required',
		PROP_addToDefaultView: 'Add to the default view',
		PROP_fieldDisplayName: 'The display name of the field',
		PROP_formatterJSON: 'The formatter JSON'
	};
});
