define([], function() {
	return {
		PropertyPaneDescription: 'Configure the WebPart settings',
		SettingsGroupName: 'Settings',
		SchemaPropertyButtonLabel: 'Configure Site Designs Schema',
		SchemaPropertyEditorCancelButtonLabel: 'Cancel',
    SchemaPropertyEditorOkButtonLabel: 'Ok',
    SchemaPropertyEditorResetButtonLabel: 'Reset to default Schema',
		SchemaPropertyEditorDialogTitle: 'Set the schema',
    PropertyIsComplexTypeMessage: 'This value is a complex object type',
    WizardsPropertyGroup: 'Wizards',
    UseWizardActionGeneratorLabel: 'Use Action Generators',
    UseWizardPropertyEditorLabel: 'Use smart Property Editors',
		UseJsonEditorMessage: 'Use the JSON editor instead',
		NoAvailableThemes: 'No available themes...',
		NoAvailableHubSites: 'No available hub sites...',
		LoadingLabel: 'Loading...',
		Schema_Action_createSPList_setTitle_Title: 'Set the title',
		Schema_Action_createSPList_setDescription_Title: 'Set the description',
		Schema_Action_createSPList_addSPField_Title: 'Add a field',
		Schema_Action_createSPList_deleteSPField_Title: 'Delete a field',
		Schema_Action_createSPList_addContentType_Title: 'Add a Content Type',
		Schema_Action_createSPList_removeContentType_Title: 'Remove a Content Type',
		Schema_Action_createSPList_setSPFieldCustomFormatter_Title: 'Set a field custom formatter',
		Schema_Action_createSPList_Title: 'Create a List',
		Schema_Action_addNavLink_Title: 'Add a navigation link',
		Schema_Action_applyTheme_Title: 'Apply a theme',
		Schema_Action_setSiteLogo_Title: 'Set the Site Logo',
		Schema_Action_joinHubSite_Title: 'Join a Hub Site',
		Schema_Action_triggerFlow_Title: 'Trigger a Flow',
		Schema_Action_setSiteExternalSharingCapability_Title: 'Set site external sharing capability',
		Schema_Action_createSPList_createSPList_setTitle_Desc: 'Set the title of the list',
		Schema_Action_createSPList_createSPList_setDescription_Desc: 'Set the description of the list',
		Schema_Action_createSPList_createSPList_addSPField_Desc: 'Add a field to the list',
		Schema_Action_createSPList_createSPList_deleteSPField_Desc: 'Delete a field from the list',
		Schema_Action_createSPList_createSPList_addContentType_Desc:
			'Add one of the available Site Content Types to the list',
		Schema_Action_createSPList_createSPList_removeContentType_Desc: 'Remove a Content Type from the list',
		Schema_Action_createSPList_createSPList_setSPFieldCustomFormatter_Desc:
			'Set a custom formatter for a specific field',
		Schema_Action_createSPList_createSPList_Desc: 'Create in list in the current site',
		Schema_Action_createSPList_addNavLink_Desc: 'Add a Navigation Link to the current site',
		Schema_Action_createSPList_applyTheme_Desc: 'Apply a custom theme to the current site',
		Schema_Action_createSPList_setSiteLogo_Desc: 'Set the logo of the current site',
		Schema_Action_createSPList_joinHubSite_Desc: 'Make the current site join a specified Hub Site',
		Schema_Action_createSPList_triggerFlow_Desc: 'Trigger the specified Microsoft Flow',
		Schema_Action_createSPList_setSiteExternalSharingCapability_Desc:
			'Set the external sharing capability of the site',
		Schema_createSPList_setTitle_title_Title: 'Title',
		Schema_createSPList_setDescription_description_Title: 'Description',
		Schema_createSPList_addSPField_fieldType_Title: 'Field Type',
		Schema_createSPList_addSPField_displayName_Title: 'Display Name',
		Schema_createSPList_addSPField_isRequired_Title: 'Is required',
		Schema_createSPList_addSPField_addToDefaultView_Title: 'Add to default view',
		Schema_createSPList_deleteSPField_displayName_Title: 'Display Name',
		Schema_createSPList_addContentType_name_Title: "Content Type's name",
		Schema_createSPList_removeContentType_name_Title: "Content Type's name",
		Schema_createSPList_setSPFieldCustomFormatter_fieldDisplayName_Title: "Field's display name",
		Schema_createSPList_setSPFieldCustomFormatter_formatterJSON_Title: 'The formatter JSON',
		Schema_createSPList_listName_Title: "List's name",
		Schema_createSPList_templateType_Title: "List's Template Type",
		Schema_createSPList_subactions_Title: 'Sub actions',
		Schema_addNavLink_url_Title: "Link's URL",
		Schema_addNavLink_displayName_Title: "Link's text",
		Schema_addNavLink_isWebRelative_Title: 'Is Web Relative',
		Schema_applyTheme_themeName_Title: "Theme's name",
		Schema_setSiteLogo_url_Title: "Site logo's URL",
		Schema_joinHubSite_hubSiteId_Title: 'Hub Site',
		Schema_triggerFlow_url_Title: "Flow's URL",
		Schema_triggerFlow_name_Title: "Flow's name",
		Schema_triggerFlow_parameters_Title: "Flow's parameters",
		Schema_setSiteExternalSharingCapability_capability_Title: 'External sharing capability',
		Schema_createSPList_setTitle_title_Desc: 'Title of the list',
		Schema_createSPList_setDescription_description_Desc: 'Description of the list',
		Schema_createSPList_addSPField_fieldType_Desc: 'The type of the field',
		Schema_createSPList_addSPField_displayName_Desc: 'The displayed name of the field',
		Schema_createSPList_addSPField_isRequired_Desc: 'Is the field required',
		Schema_createSPList_addSPField_addToDefaultView_Desc: 'The field is added to default view',
		Schema_createSPList_deleteSPField_displayName_Desc: 'The displayed name of the field',
		Schema_createSPList_addContentType_name_Desc: 'The name of an existing Site Content Type',
		Schema_createSPList_removeContentType_name_Desc: 'The name of the Content Type',
		Schema_createSPList_setSPFieldCustomFormatter_fieldDisplayName_Desc:
			'The display name of the field to apply the formatting on',
		Schema_createSPList_setSPFieldCustomFormatter_formatterJSON_Desc: 'The formatter rules expressed in JSON',
		Schema_createSPList_listName_Desc: 'The name of the List',
		Schema_createSPList_templateType_Desc: 'The template type of the list',
		Schema_createSPList_subactions_Desc: 'Define the sub actions of the Create List action',
		Schema_addNavLink_url_Desc: 'The URL of the navigation Link',
		Schema_addNavLink_displayName_Desc: 'The text of the navigation Link',
		Schema_addNavLink_isWebRelative_Desc: 'Is the URL of the link web-relative ?',
		Schema_applyTheme_themeName_Desc: 'The name of the custom theme to apply',
		Schema_setSiteLogo_url_Desc: 'The URL of the Site logo',
		Schema_joinHubSite_hubSiteId_Desc: 'The identifier of the Hub Site',
		Schema_triggerFlow_url_Desc: 'The URL of the Flow to trigger',
		Schema_triggerFlow_name_Desc: 'The name of the Flow to trigger',
		Schema_triggerFlow_parameters_Desc: 'The set of parameters of the Flow',
		Schema_setSiteExternalSharingCapability_capability_Desc: 'The defined external sharing capability'
	};
});
